// <auto-generated />
using System;
using Kolos_2_poprawa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos_2_poprawa.Migrations
{
    [DbContext(typeof(RentalContext))]
    [Migration("20240625110812_test002")]
    partial class test002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolos_2_poprawa.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelId");

                    b.ToTable("cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 3,
                            ModelId = 2,
                            Name = "Toyota Yaris",
                            PricePerDay = 120,
                            Seats = 5,
                            VIN = "2D4HN11EX9R686008"
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 2,
                            ModelId = 3,
                            Name = "Skoda Fabia Estate",
                            PricePerDay = 170,
                            Seats = 5,
                            VIN = "JTDBR32E630013672"
                        });
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.CarRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("car_rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ClientId = 1,
                            DateFrom = new DateTime(2024, 6, 25, 13, 8, 12, 532, DateTimeKind.Local).AddTicks(7720),
                            DateTo = new DateTime(2024, 6, 30, 13, 8, 12, 532, DateTimeKind.Local).AddTicks(7790),
                            TotalPrice = 480
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            ClientId = 1,
                            DateFrom = new DateTime(2024, 6, 25, 13, 8, 12, 532, DateTimeKind.Local).AddTicks(7800),
                            DateTo = new DateTime(2024, 6, 30, 13, 8, 12, 532, DateTimeKind.Local).AddTicks(7800),
                            Discount = 50,
                            TotalPrice = 240
                        },
                        new
                        {
                            Id = 3,
                            CarId = 2,
                            ClientId = 1,
                            DateFrom = new DateTime(2024, 6, 25, 13, 8, 12, 532, DateTimeKind.Local).AddTicks(7800),
                            DateTo = new DateTime(2024, 6, 30, 13, 8, 12, 532, DateTimeKind.Local).AddTicks(7800),
                            TotalPrice = 1700
                        });
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Koszykowa 63",
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Złota 44",
                            FirstName = "Anna",
                            LastName = "Nowa"
                        });
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "red"
                        },
                        new
                        {
                            Id = 2,
                            Name = "black"
                        },
                        new
                        {
                            Id = 3,
                            Name = "white"
                        });
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Skoda"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ford"
                        });
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Car", b =>
                {
                    b.HasOne("Kolos_2_poprawa.Models.Color", "Color")
                        .WithMany("cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kolos_2_poprawa.Models.Model", "Model")
                        .WithMany("cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.CarRental", b =>
                {
                    b.HasOne("Kolos_2_poprawa.Models.Car", "Car")
                        .WithMany("rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kolos_2_poprawa.Models.Client", "Client")
                        .WithMany("rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Car", b =>
                {
                    b.Navigation("rentals");
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Client", b =>
                {
                    b.Navigation("rentals");
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Color", b =>
                {
                    b.Navigation("cars");
                });

            modelBuilder.Entity("Kolos_2_poprawa.Models.Model", b =>
                {
                    b.Navigation("cars");
                });
#pragma warning restore 612, 618
        }
    }
}
